require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'DJRainMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # To enable Hermes on iOS, change false to true and then install pods
    :hermes_enabled => false
  )

  target 'DJRainMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  # Disable Fabric components
  $ReactNativeFabricEnabled = false

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0' # or the version you need
      end
    end
  end
end
